<?php
/**
 * @file
 * Provides custom tokens
 *
 * @see httx://drupal.org/node/1308488
 */

/**
 * Implementation of hook_menu() to create Custom Tokens admin screen
 */
function cmc_custom_tokens_menu() {
	$items = array();

	$items['admin/config/cmc/custom_tokens'] = array(
		'title' => 'CMC Custom Tokens',
		'description' => 'CMC Custom Tokens Configuration',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('cmc_custom_tokens_settings'),
		'access arguments' => array('Configure CMC Custom Tokens'),
		'type' => MENU_NORMAL_ITEM,
	);

	return $items;
}

/**
 * Implementation of hook_permission() to create 'Configure CMC Custom Tokens' permission
 */
function cmc_custom_tokens_permission() {
	return array(
		'Configure CMC Custom Tokens' => array(
			'title' => t('Configure CMC Custom Tokens'),
		),
	);
}


/**
 * Configurable settings for the Custom Settings that can be set within the Drupal admin
 */
function cmc_custom_tokens_settings() {

	$form['token_values'] = array(
		'#type' => 'fieldset',
		'#title' => 'Token Values',
		'#collapsible' => TRUE,
		'#collapsed' => FALSE,
	);
	$form['token_values']['live_spreadbet_login_link'] = array(
       '#type'           => 'textfield',
       '#title'          => t('Live Spreadbet Login Link'),
       '#default_value'  => variable_get('live_spreadbet_login_link', NULL),
       '#size'           => 60,
       '#description'    => t('The link to login into the Live Spread Betting platform'),
  );
	$form['token_values']['live_cfd_login_link'] = array(
       '#type'           => 'textfield',
       '#title'          => t('Live CFD Login Link'),
       '#default_value'  => variable_get('live_cfd_login_link', NULL),
       '#size'           => 60,
       '#description'    => t('The link to login into the Live CFD platform'),
  );
	$form['token_values']['demo_spreadbet_login_link'] = array(
       '#type'           => 'textfield',
       '#title'          => t('Demo Spreadbet Login Link'),
       '#default_value'  => variable_get('demo_spreadbet_login_link', NULL),
       '#size'           => 60,
       '#description'    => t('The link to login into the Demo Spread Betting platform'),
  );
	$form['token_values']['demo_cfd_login_link'] = array(
       '#type'           => 'textfield',
       '#title'          => t('Demo CFD Login Link'),
       '#default_value'  => variable_get('demo_cfd_login_link', NULL),
       '#size'           => 60,
       '#description'    => t('The link to login into the Demo CFD platform'),
  );
  
  return system_settings_form($form);
}


/**
 * Provide information about our custom placeholder/token.
 *
 * @see httx://api.drupal.org/api/drupal/modules--system--system.api.php/function/hook_token_info/7
 * @see httx://api.lullabot.com/token_example_token_info/7
 */
function cmc_custom_tokens_token_info() {
  $types['cmc'] = array(
    'name' => t("CMC Tokens"),
    'description' => t("Tokens for use on the CMC website."),
  );
  
  $cmc['live_spreadbet_login_link'] = array(
    'name' => t("Live Spreadbet Login Link"),
    'description' => t("The link to login into the Spread Betting platform."),
  );
  $cmc['live_cfd_login_link'] = array(
    'name' => t("Live CFD Login Link"),
    'description' => t("The link to login into the CFD platform."),
  );
  $cmc['demo_spreadbet_login_link'] = array(
    'name' => t("Demo Spreadbet Login Link"),
    'description' => t("The link to login into the Spread Betting platform."),
  );
  $cmc['demo_cfd_login_link'] = array(
    'name' => t("Demo CFD Login Link"),
    'description' => t("The link to login into the CFD platform."),
  );
  
  return array(
    'types' => $types,
    'tokens' => array(
      'cmc' => $cmc,
    ),
  );
}

/**
 * Provide replacement values for placeholder tokens.
 *
 * @see httx://api.drupal.org/api/drupal/modules--system--system.api.php/function/hook_tokens/7
 * @see httx://api.lullabot.com/token_example_tokens/7
 * @param string $type
 *   The machine-readable name of the type (group) of token being replaced, such
 *   as 'node', 'user', or another type defined by a hook_token_info()
 *   implementation.
 * @param array $tokens
 *   An array of tokens to be replaced. The keys are the machine-readable token
 *   names, and the values are the raw [type:token] strings that appeared in the
 *   original text.
 * @param array $data (optional)
 *   An associative array of data objects to be used when generating replacement
 *   values, as supplied in the $data parameter to token_replace().
 * @param array $options (optional)
 *   An associative array of options for token replacement; see token_replace()
 *   for possible values.
 * @return array
 *   An associative array of replacement values, keyed by the raw [type:token]
 *   strings from the original text.
 */
function cmc_custom_tokens_tokens($type, $tokens, array $data = array(), array $options = array()) {
  
  $replacements = array();
  
  $live_spreadbet_login_link = variable_get('live_spreadbet_login_link', NULL);
  $live_cfd_login_link = variable_get('live_cfd_login_link', NULL);
  $demo_spreadbet_login_link = variable_get('demo_spreadbet_login_link', NULL);
  $demo_cfd_login_link = variable_get('demo_cfd_login_link', NULL);

  if ($type == 'cmc') {
    foreach ($tokens as $name => $original) {
      switch ($name) {
        case 'live_spreadbet_login_link':
          $replacements[$original] = $live_spreadbet_login_link;
        break;
        case 'live_cfd_login_link':
          $replacements[$original] = $live_cfd_login_link;
        break;
        case 'demo_spreadbet_login_link':
          $replacements[$original] = $demo_spreadbet_login_link;
        break;
        case 'demo_cfd_login_link':
          $replacements[$original] = $demo_cfd_login_link;
        break;              }
    }
  }
  
  return $replacements;
}