<?php




function nextgen_stub_init() {
  $client = new NextgenTestClient();

  nextgen_stub_authenticate_success_1($client);
  nextgen_stub_authenticate_success_2($client);
  nextgen_stub_search_identity_no_results($client);

  nextgen_client($client);
}



function nextgen_stub_authenticate_success_1($client) {
  $data = array('identity' => 12345);

  $client->add('1.0', 'identity', 'authenticate', json_encode($data));
}

function nextgen_stub_authenticate_success_2($client) {
  $response = new AuthenticationResponse();
  $identity = new Identity(12345);
  $response->setIdentity($identity);

  $client->add('2.0', 'identity', 'authenticate', json_encode($response));
}

function nextgen_stub_search_identity_no_results($client) {
  $response = new SearchIdentityResponse();
  $response->setIdentities(array());

  $client->add('2.0', 'identity', 'searchIdentity', json_encode($response));
}