<?php

function cmc_page_uk_default_content() {
  $content = array(
  /*
    'Spreadbet' => array(
    	'Spreadbet page 1',
      'Spreadbet page 2',
      'Spreadbet page 3',
      'Spreadbet page 4',
    ),
    'CFD' => array(
      'CFD page 1',
      'CFD page 2',
      'CFD page 3',
      'CFD page 4',
    ),*/
    'Forex' => array(
      'Forex page 1',
      'Forex page 2',
      'Forex page 3',
      'Forex page 4',
    ),
    'Education' => array(
      'Education page 1',
      'Education page 2',
      'Education page 3',
      'Education page 4',
    ),
    'Section' => array(
      'Section page 1',
      'Section page 2',
      'Section page 3',
      'Section page 4',
    ),
  );
  return $content;
}