<?php

/*
  Implementation of hook_menu()
*/
function cmc_framework_menu() {
  $items = array();

  $items['admin/config/cmc'] = array(
    'title' => 'CMC',
    'description' => 'CMC Markets Configuration',
    'position' => 'left',
    'weight' => -100,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer site configuration'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  
  $items['admin/config/cmc/risk_warning'] = array(
    'title' => 'CMC Risk Warning',
    'description' => 'CMC Risk Warning Configuration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cmc_framework_risk_warning_settings'),
    'access arguments' => array('administer cmc_risk_warning'),
  	'file' => 'includes/cmc_risk_warning.inc',
  );
  
  $items['admin/config/cmc/open_account'] = array(
    'title' => 'CMC Open Account',
    'description' => 'CMC Open Account Configuration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cmc_framework_open_account_settings'),
    'access arguments' => array('administer cmc_open_account'),
    'file' => 'includes/cmc_open_account.inc',
  );
  
  $items['admin/config/cmc/seo_footer'] = array(
    'title' => 'CMC SEO Footer',
    'description' => 'CMC SEO Footer Configuration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cmc_framework_seo_footer_settings'),
    'access arguments' => array('administer cmc_seo_footer'),
    'file' => 'includes/cmc_seo_footer.inc',
  );
  
  $items['admin/config/cmc/login'] = array(
    'title' => 'CMC login',
    'description' => 'CMC Login Configuration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cmc_framework_login_settings'),
    'access arguments' => array('administer cmc_login'),
    'file' => 'includes/cmc_login.inc',
  );
  
  $items['admin/config/cmc/country_switcher'] = array(
    'title' => 'CMC Country Switcher',
    'description' => 'CMC Switcher Configuration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cmc_framework_country_switcher_settings'),
    'access arguments' => array('administer cmc_country_switcher'),
    'file' => 'includes/cmc_country_switcher.inc',
  );
  
  $items['admin/config/cmc/signup'] = array(
    'title' => 'CMC Signup',
    'description' => 'CMC Signup Configuration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cmc_framework_signup_settings'),
    'access arguments' => array('administer cmc_signup'),
    'file' => 'includes/cmc_signup.inc',
  );
  
  $items['admin/config/cmc/contact'] = array(
    'title' => 'CMC Contact',
    'description' => 'CMC Contact Configuration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cmc_framework_contact_settings'),
    'access arguments' => array('administer cmc_contact'),
    'file' => 'includes/cmc_contact.inc',
  );
  
  $items['admin/config/cmc/markets_landing'] = array(
    'title' => 'CMC Markets Landing',
    'description' => 'CMC Markets Landing Configuration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cmc_framework_markets_landing_settings'),
    'access arguments' => array('administer cmc_markets_landing'),
    'file' => 'includes/cmc_markets_landing.inc',
  );
  
  $items['admin/config/cmc/emailvision'] = array(
    'title' => 'CMC Markets Email Vision',
    'description' => 'CMC Markets Emailvision Configuration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cmc_framework_emailvision_settings'),
    'access arguments' => array('administer cmc_emailvision'),
    'file' => 'includes/cmc_emailvision.inc',
  );
  
  $items['admin/config/cmc/follow'] = array(
    'title' => 'CMC Markets Follow',
    'description' => 'CMC Markets Follow Us Configuration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cmc_framework_follow_settings'),
    'access arguments' => array('administer cmc_follow'),
    'file' => 'includes/cmc_follow.inc',
  );
  

  return $items;
}


/**
 * hook_init
 */
function cmc_framework_init() {

  $domain = domain_get_domain();
  $domain_info = domain_lookup($domain['domain_id']);
  drupal_add_js(array('cmc' =>
      array(
        'domain' => $domain_info['machine_name']
      )
    ),
    array('type' => 'setting', 'every_page' => TRUE)
  );

}



/**
 * Implementation of hook_perm().
 */
function cmc_framework_permission() {
  return array(
    'administer cmc_risk_warning' => array(
      'title' => t('administer cmc_risk_warning'),
      'restrict access' => TRUE,
     ),
     'administer cmc_open_account' => array(
      'title' => t('administer cmc_open_account'),
      'restrict access' => TRUE,
     ),
     'administer cmc_seo_footer' => array(
      'title' => t('administer cmc_seo_footer'),
      'restrict access' => TRUE,
     ),
     'administer cmc_login' => array(
      'title' => t('administer cmc_login'),
      'restrict access' => TRUE,
     ),
     'administer cmc_country_switcher' => array(
      'title' => t('administer cmc_country_switcher'),
      'restrict access' => TRUE,
     ),
     'administer cmc_signup' => array(
      'title' => t('administer cmc_signup'),
      'restrict access' => TRUE,
     ),
     'administer cmc_contact' => array(
      'title' => t('administer cmc_contact'),
      'restrict access' => TRUE,
     ),
     'administer cmc_markets_landing' => array(
      'title' => t('administer cmc_markets_landing'),
      'restrict access' => TRUE,
     ),
     'administer cmc_emailvision' => array(
      'title' => t('administer cmc_emailvision'),
      'restrict access' => TRUE,
     ),
     'administer cmc_follow' => array(
      'title' => t('administer cmc_follow'),
      'restrict access' => TRUE,
     ),
  );
}





/**
 * hook_block_info
 */
function cmc_framework_block_info() {
  $blocks['cmc_open_account'] = array(
    'info' => t('CMC Open Account'),
  );
  
  $blocks['cmc_risk_warning'] = array(
    'info' => t('CMC Risk Warning'),
  );
  
  $blocks['cmc_seo_footer'] = array(
    'info' => t('CMC SEO Footer'),
  );
  
  $blocks['cmc_top'] = array(
    'info' => t('CMC Top'),
  );
  
  $blocks['cmc_bottom'] = array(
    'info' => t('CMC Bottom'),
  );
  
  $blocks['cmc_signup'] = array(
    'info' => t('CMC Signup'),
  );
  
  $blocks['cmc_back_to_results'] = array(
    'info' => t('CMC Back to results'),
  );
  
  $blocks['cmc_contact_map'] = array(
    'info' => t('CMC Contact Us Map'),
  );
  
  $blocks['cmc_contact_form'] = array(
    'info' => t('CMC Contact Us Form'),
  );
  
  $blocks['cmc_share_this'] = array(
    'info' => t('CMC Share This'),
  );
  
  $blocks['cmc_markets_landing'] = array(
    'info' => t('CMC Markets Landing'),
  );
  
  $blocks['cmc_follow'] = array(
    'info' => t('CMC Follow Us'),
  );
  
    
  return $blocks;
}


/**
 * hook_block_view
 * @param unknown_type $delta
 */
function cmc_framework_block_view($delta = '') {
  //$path = drupal_get_path('module', 'cmc_framework');
$block = array();
  if ($delta == 'cmc_open_account') {
    module_load_include('inc', 'cmc_framework', 'includes/cmc_open_account');
    $block['content'] = cmc_framework_open_account_block();
  }
  else if ($delta == 'cmc_risk_warning') {
    module_load_include('inc', 'cmc_framework', 'includes/cmc_risk_warning');
    $block['content'] = cmc_framework_risk_warning_block();
  }
  else if ($delta == 'cmc_seo_footer') {
    module_load_include('inc', 'cmc_framework', 'includes/cmc_seo_footer');
    $block['content'] = cmc_framework_seo_footer_block();
  }
  else if ($delta == 'cmc_bottom') {
    module_load_include('inc', 'cmc_framework', 'includes/cmc_bottom');
    $block['content'] = cmc_framework_bottom_block();
  }
  else if ($delta == 'cmc_top') {
    module_load_include('inc', 'cmc_framework', 'includes/cmc_top');
    $block['content'] = cmc_framework_top_block();
  }
  else if ($delta == 'cmc_signup') {
    module_load_include('inc', 'cmc_framework', 'includes/cmc_signup');
    $block['content'] = cmc_framework_signup_block();
  }
  else if ($delta == 'cmc_back_to_results') {
    module_load_include('inc', 'cmc_framework', 'includes/cmc_back_to_results');
    $block['content'] = cmc_framework_back_to_results_block();
  }
  else if ($delta == 'cmc_contact_map') {
    module_load_include('inc', 'cmc_framework', 'includes/cmc_contact');
    $block['content'] = cmc_framework_contact_map_block();
  }
  else if ($delta == 'cmc_contact_form') {
    module_load_include('inc', 'cmc_framework', 'includes/cmc_contact');
    $block['content'] = cmc_framework_contact_form_block();
  }
  else if ($delta == 'cmc_share_this') {
    module_load_include('inc', 'cmc_framework', 'includes/cmc_share_this');
    $block['content'] = cmc_framework_share_this_block();
  }
  else if ($delta == 'cmc_markets_landing') {
    module_load_include('inc', 'cmc_framework', 'includes/cmc_markets_landing');
    $block['content'] = cmc_framework_markets_landing_block();
  }
  else if ($delta == 'cmc_follow') {
    module_load_include('inc', 'cmc_framework', 'includes/cmc_follow');
    $block['content'] = cmc_framework_follow_block();
  }
  

  return $block;
}


/**
 * Top block
 */
function cmc_framework_top_block() {
  
  $data = array();

	module_load_include('inc', 'cmc_framework', 'includes/cmc_login');
  $data['login'] = cmc_framework_login_block();
  
  $search_block = module_invoke('search', 'block_view', '');
  $data['search'] = render($search_block['content']);
  return theme('cmc_top', array('data' => $data));
}


/**
 * Bottom block
 */
function cmc_framework_bottom_block() {
  
	$data = array();

  //$data['country_switcher'] = cmc_framework_country_switcher_block();
  module_load_include('inc', 'cmc_framework', 'includes/cmc_country_switcher');
  $data['country_switcher'] = cmc_framework_country_switcher_block();


  
  $menu_block = module_invoke('cmc_domain', 'block_view', 'cmc_domain_footer_menu');
  $data['menu'] = render($menu_block['content']);
  
  return theme('cmc_bottom', array('data' => $data));
}



/**
 * hook_theme
 */
function cmc_framework_theme($existing, $type, $theme, $path) {
  return array(
    'cmc_risk_warning' => array(
      'template'	=> 'theme/cmc_risk_warning',
      'variables' => array(
        'data' => NULL
      ),
    ),
    'cmc_open_account' => array(
      'template'	=> 'theme/cmc_open_account',
      'variables' => array(
        'data' => NULL
      ),
    ),
    'cmc_seo_footer' => array(
      'template'	=> 'theme/cmc_seo_footer',
      'variables' => array(
        'data' => NULL
      ),
    ),
    'cmc_login' => array(
      'template'	=> 'theme/cmc_login',
      'variables' => array(
        'data' => NULL
      ),
    ),
    'cmc_country_switcher' => array(
      'template'	=> 'theme/cmc_country_switcher',
      'variables' => array(
        'data' => NULL
      ),
    ),
    'cmc_bottom' => array(
      'template'	=> 'theme/cmc_bottom',
      'variables' => array(
        'data' => NULL
      ),
    ),
    'cmc_top' => array(
      'template'	=> 'theme/cmc_top',
      'variables' => array(
        'data' => NULL
      ),
    ),
    'cmc_signup' => array(
      'template'	=> 'theme/cmc_signup',
      'variables' => array(
        'data' => NULL
      ),
    ),
    'cmc_back_to_results' => array(
      'template'	=> 'theme/cmc_back_to_results',
      'variables' => array(
        'data' => NULL
      ),
    ),
    'cmc_contact_map' => array(
      'template'	=> 'theme/cmc_contact_map',
      'variables' => array(
        'data' => NULL
      ),
    ),
    'cmc_contact_form' => array(
      'template'	=> 'theme/cmc_contact_form',
      'variables' => array(
        'data' => NULL
      ),
    ),
    'cmc_share_this' => array(
      'template'	=> 'theme/cmc_share_this',
      'variables' => array(
        'data' => NULL
      ),
    ),
    'cmc_markets_landing' => array(
      'template'	=> 'theme/cmc_markets_landing',
      'variables' => array(
        'data' => NULL
      ),
    ),
    'cmc_follow' => array(
      'template'	=> 'theme/cmc_follow',
      'variables' => array(
        'data' => NULL
      ),
    ),
    
    
  );
}


/**
 * use hook_form_alter to modify the sitemap settings form
 */
function cmc_framework_form_site_map_admin_settings_form_alter(&$form, &$form_state, $form_id) {

  $form['cmc_sitemap_menu_order'] = array(
    '#type' => 'fieldset',
    '#title' => t('Sitemap Menu Order'),
    '#collapsible' => FALSE,
    '#collapsed' => FALSE,
  );
  
  $form['cmc_sitemap_menu_order']['cmc_sitemap_help'] = array(
    '#markup' => 'Choose menus in site map content and save.<br />'
    . 'The menus should then appear here and can be re-ordered.',
  );
  
  $mids = array_filter(variable_get('site_map_show_menus', array()));
  $options = array();
  $num_menus = count(variable_get('site_map_show_menus', array()));
  for ($i=1; $i<=$num_menus; $i++) {
    $options[$i] = $i;
  }
  
  // get all the menus so we display the menu names in a more
  // human readable format
  $result = db_query("SELECT * FROM {menu_custom} ORDER BY title", array(), array('fetch' => PDO::FETCH_ASSOC));
  $menus = array();
  foreach ($result as $menu) {
    $menus[$menu['menu_name']] = $menu;
  }
  
      
  $i=0;
  foreach ($mids as $k => $v) {
    $key = 'cmc_sitemap_' . $k;
    $form['cmc_sitemap_menu_order'][$key] = array(
      '#type' => 'select',
      '#options' => $options,
      '#title' => $menus[$k]['title'] . t(' sitemap order'),
      '#default_value' => variable_get($key, ''),
    );
    
    $i++;
  }

}


/**
 * Preprocesses the variables for site-map.tpl.php.
 * Copied from site_map.theme.inc
 *
 * @see site-map.tpl.php
 */
function cmc_framework_preprocess_site_map(&$variables) {
  
  $message = variable_get('site_map_message', array());
  if (!empty($message)) {
    $variables['message'] = check_markup($message['value'], $message['format']);
  }

  if ((variable_get('site_map_show_rss_links', 1) != 0) && module_exists('commentrss') && variable_get('commentrss_site', COMMENTRSS_SITE_FRONT_PAGE)) {
    $variables['rss_legend'] = theme('site_map_rss_legend');
  }

  if (variable_get('site_map_show_front', 1)) {
    $variables['front_page'] = _site_map_front_page();
  }

  if (variable_get('site_map_show_blogs', 1)) {
    $variables['blogs'] = _site_map_blogs();
  }

  // Compile the books trees.
  $variables['books'] = _site_map_books();

  // Compile the menu trees.
  //$variables['menus'] = _site_map_menus();
  // customised menu function as we order them
  $variables['menus'] = _cmc_framework_site_map_menus();
  
  if (variable_get('site_map_show_faq', 0)) {
    $variables['faq'] = _site_map_faq();
  }

  // Compile the vocabulary trees.
  $variables['taxonomys'] = _site_map_taxonomys();

  // Invoke all custom modules and get themed HTML to be integrated into the site map.
  $additional = module_invoke_all('site_map');
  foreach ($additional as $themed_site_map_code) {
    $variables['additional'] .= $themed_site_map_code;
  }
}


/**
 * Render menus
 * Copied and modified from site_map.module
 */
function _cmc_framework_site_map_menus() {
  $output = '';
  $class = array();
  $mids = array_filter(variable_get('site_map_show_menus', array()));
  
  if (!empty($mids)) {

    // now we order the menus according to the settigns in the
    // sitemap settings config form
    $ordered = array();
    foreach ($mids as $mid) {
      $key = 'cmc_sitemap_' . $mid;
      $order = variable_get($key, '');
      $ordered[$mid] = $order;
    }
    
    asort($ordered);
    $mids = $ordered;
    foreach (array_keys($ordered) as $k) {
      $mids[$k] = $k;
    }
    
    // output the menus
    foreach ($mids as $mid) {
      $menu = menu_load($mid);
      // Use menu_tree_all_data to retrieve the expanded tree.
      $tree = menu_tree_all_data($mid);
      if (module_exists('i18n_menu')) {
        $tree = i18n_menu_localize_tree($tree, $GLOBALS['language']->language);
      }
      $menu_display = _site_map_menu_tree_output($tree);
      $menu_html = drupal_render($menu_display);
      if (!empty($menu_html)) {
        //$title = $menu['title'];
        $title = ''; // don't want titles to show for menus
        $class[] = 'site-map-box-menu';
        $class[] = 'site-map-box-menu-' . $mid;
        $attributes = array('class' => $class);
        $output .= theme('site_map_box', array('title' => $title, 'content' => $menu_html, 'attributes' => $attributes));
      }
    }
  }

  return $output;
}


function cmc_framework_formatted_textarea_defaults($text) {
  return array(
    'format' => 'cmc_editor',
  	'value' => $text,
  );
}


/**
 * hook_node_view
 * Insert some stuff for emailvision into the node view
 */
function cmc_framework_node_view(&$node, $view_mode, $langcode) {

  $emailvision_optout_node = variable_get('cmc_framework_emailvision_optout_node', '3991');
  
  if ($node->nid == $emailvision_optout_node) {
    // append js to the body
    $emailvision_optout_js = variable_get('cmc_framework_emailvision_optout_js', 'Some script');
    $node->content['body'][0]['#markup'] .= $emailvision_optout_js;
  }
}






