<?php
/**
 * @file
 * Code for the CMC Document Guide feature.
 */

include_once('cmc_document_guide.features.inc');
include_once('cmc_document_guide.webform.inc');

function cmc_document_guide_menu() {
  $items = array();
  
  $items['node/%node/cmc_document_guide_webform'] = array(
    'title' => 'Export Registrations',
    'page callback' => 'cmc_document_guide_webform_export',
    'page arguments' => array(1),
    'access callback' => 'cmc_document_guide_access',
    'access arguments' => array(1, 'Access all webform results'),
    'file' => 'cmc_document_guide.webform.inc',
    'weight' => 9,
    'type' => MENU_LOCAL_TASK,
  );
  
  $items['node/%node/cmc_document_guide_webform/download'] = array(
    'title' => 'Download Registrations',
    'page callback' => 'cmc_document_guide_webform_download',
    'page arguments' => array(1),
    'access callback' => 'cmc_document_guide_access',
    'access arguments' => array(1, 'Access all webform results'),
    'file' => 'cmc_document_guide.webform.inc',
    
  );
  
  return $items;
}


function cmc_document_guide_access($node, $perm) {
  if ($node->type == 'cmc_document_guide') {
    if (user_access($perm)) {
      return true;
    }
  }
  return false;
}

/**
 * hook_node_view
 *
 * @param unknown_type $node
 * @param unknown_type $view_mode
 * @param unknown_type $langcode
 */
function cmc_document_guide_node_view(&$node, $view_mode, $langcode) {

  if ($node->type != 'cmc_document_guide') {
    return;
  }
  
  // check if we should show the webform
  $view = views_get_view('cmc_document_guide');
  $view->preview('webform_nid', array($node->nid));

  if (!empty($view->result[0])) {
    $webform_nid = $view->result[0]->field_field_webform[0]['raw']['nid'];
    $block = module_invoke('webform', 'block_view', 'client-block-' . $webform_nid);
    $node->content['body'][0]['#markup'] .= render($block['content']);
  }
}


/**
 * hook_form_alter
 */
function cmc_document_guide_form_alter(&$form, &$form_state, $form_id) {
  
  if (module_exists('cmc_webform') && cmc_webform_is_embedded_webform($form)) {
    // if we're on an event node and have embedded an webform
    
    if (!is_numeric(arg(1))) {
      return;
    }
    $document_guide_node = node_load(arg(1));
    
    if ($document_guide_node->type == 'cmc_document_guide') {

      $webform_replace_values = array(
        'cmc_document_guide_nid' => 'nid',
        'cmc_document_guide_title' => 'title',
      );
      
      foreach ($webform_replace_values as $webform_key => $node_prop) {
        if (isset($form['submitted'][$webform_key]['#default_value'])) {
          $form['submitted'][$webform_key]['#default_value'] = $document_guide_node->{$node_prop};
        }
      }
    }
    
  }
}
