<?php

/**
   Implementation of hook_permission
*/
function translation_dashboard_permission() {
  return array(
    'administer translations' => array(
      'title' => t('Administer translations via the Translation Dashboard'),
      'description' => t('Translate interface and content strings into multiple languages')
    )
  );
}


/**
   Implementation of hook_menu()
*/
function translation_dashboard_menu() {
  $items = array();

  $items['admin/config/regional/translate/dasbboard'] = array(
    'title' => 'Translation Dashboard',
    'description' => 'Translate interface and content strings into multiple languages',
    'page callback' => 'translation_dashboard_overview',
    'access arguments' => array('administer translations'),
    'file' => 'translation_dashboard.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );

  $items['admin/config/regional/translations/edit/%/%'] = array(
    'title' => 'Edit Translation',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('translation_dashboard_edit_form', 5, 6),
    'access arguments' => array('administer translations'),
    'type' => MENU_CALLBACK,
    'file' => 'translation_dashboard.admin.inc'
  );

  return $items;
}
